version: '3'

services:
  streamlit-app:
    build: .
    container_name: brain-disorder-ml-analysis
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
